version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: doewe-postgres
    environment:
      POSTGRES_USER: doewe
      POSTGRES_PASSWORD: doewe
      POSTGRES_DB: doewe_local
    ports:
      - "5432:5432"
    volumes:
      - doewe_pg_data:/var/lib/postgresql/data

volumes:
  doewe_pg_data:
